### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by wpsumo** [Remzi1993/wp-jquery-manager#47]
**Describe the bug**
Console error `Uncaught TypeError: e.indexOf is not a function`

**To conflict**
Oxygen builder
WP asset cleanup

Looks like it's a conflict with WP asset cleanup. Let me know if it's on his end and I will report the bug to him instead

**Screenshots**
![image](https://user-images.githubusercontent.com/16893128/76701390-665c3500-66c9-11ea-8504-e8634ff494c8.png)

```
jquery-3.4.1.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at k.fn.init.k.fn.load (jquery-3.4.1.min.js:2)
    at HTMLDocument.<anonymous> (script.min.js?wpacuversion=1583679921:1)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
```

**Comment by Remzi1993** [comment]
Hi @alriksson I will check this out in the coming weeks. I'm not working fulltime and due to the Corona virus outbreak home. It is most likely on them, because we use standard WP API's.

This what this plugin does by default: https://github.com/Remzi1993/jquery-manager/blob/f242457f11a435e4a799b351196a813948b4569b/jquery-manager.php#L478

Show them this link.

EDIT: same with jQuery Migrate: https://github.com/Remzi1993/jquery-manager/blob/f242457f11a435e4a799b351196a813948b4569b/jquery-manager.php#L542

**Comment by wpsumo** [comment]
@Remzi1993 Hope you are well these days!

Okay, let me know what you find and if we easy can guide the conflict to respectively plugin developer.

Be safe!
